### ISSUE TITLE
CORS Missing Allow Origin 오류 처리 요청

### ISSUE THREAD

**Issue by hatchling13** [smileostrich/bluesky-api-client#1]
# 개요
현재 프론트엔드에서 사용 중인 도구 Vite는 [HMR](https://vitejs-kr.github.io/guide/features.html#hot-module-replacement)을 위해 별도의 로컬 서버를 실행하는 식으로 동작하고 있습니다.
해당 서버는 별도의 포트를 점유하고 있으며, 따라서 백엔드와 서로 다른 Origin을 가지고 있습니다.
때문에 백엔드 서버에서 Access-Control-Allow-Origin 헤더 설정이 완료되어야 합니다.
백엔드 저장소를 살펴본 [결과](https://github.com/search?q=repo%3Asmileostrich%2Fbsky-bridge+Cors&type=code), 관련 작업 내용을 찾아볼 수 없어 해당 부분을 수정해주시길 요청드립니다.

**Comment by smileostrich** [comment]
해당 부분은 [여기](https://github.com/smileostrich/bsky-helper) 참고해주시면 좋을것 같습니다 :)

**Comment by hatchling13** [comment]
해당 문제의 발생 원인은 프론트엔드에서 API를 호출할 때 헤더를 올바르게 지정해주지 않았기 때문이었습니다.
JSON 파일을 전송할 때 헤더에 별도로 `Content-Type`을 설정해주지 않아 body가 `text/plain`으로 전송되어 오류가 발생한 것으로 확인됩니다.

답변 및 교차 확인 감사합니다, 해당 이슈는 닫음 처리하도록 하겠습니다!
